### ISSUE TITLE
WorldEditArt_Dev wont install to my server once again

### ISSUE THREAD

**Issue by AgentH14** [LegendOfMCPE/WorldEditArt#15]
WorldEditArt_Dev wont install to my server once again.  Im using a server hosting site called HostingItAll.com 

Can you help me out again.  Sorry about this though....

**Comment by KDOA808** [comment]
Not ready

**Comment by PEMapModder** [comment]
Please visit the Gitter chatroom for support. Issue tracker is not a forum or support channel.
