### ISSUE TITLE
Paint

### ISSUE THREAD

**Issue by ghost** [LegendOfMCPE/WorldEditArt#16]
I wanted to implement Shogi's paint my lawn plugin! Well, not exactly. I don't want to implement the plugin itself (Big duh) I want to implement it's features. This is kind of a stretch but there is a paint brush icon by the WorldEditArt logo. Okay, so I want to explain how this works because it's a little different.
1) The editor colors a block, any block
2) You have access to all the rgb color codes  R, G, B, H, S, V
3) You can do // pos 1 and // pos 2 then, do /paintedit 1 2 3 4 5 6 (really doesn't matter how you type the command) fill in a specified selection of blocks.

**Comment by PEMapModder** [comment]
Only grass blocks can be colored.

**Comment by ghost** [comment]
Fine, but try to add color to the entire block if possible.

**Comment by PEMapModder** [comment]
Entire block? You mean entire selection, right?

**Comment by ghost** [comment]
No, I mean... lol. I want the whole block to be one color, as if it is a new block. And, yes, i want it to apply to the whole selection.

**Comment by PEMapModder** [comment]
You mean, you want all 6 faces to be one color, right? No. The principle of PaintMyLawn is to change the biome grass color just at that position. You aren't changing the texture of the grass block, just the color of the grass part of the grass block.

**Comment by SOF3** [comment]
This feature is more appropriately implemented in [BlockSniper](https://github.com/BlockHorizons/BlockSniper). I'll pass this to @Sandertv.
