### ISSUE TITLE
Can you make it fore genisys to ?

### ISSUE THREAD

**Issue by lolcraftboy14** [LegendOfMCPE/WorldEditArt#17]
It says that you need pocketmine mp but pocketmine is dead but Can you make it fore it fore genisys plz

**Comment by PEMapModder** [comment]
The whole PocketMine-related community is dead. There is no difference, PocketMine, Genisys, ClearSky, etc. They are all dead.

**Comment by robske110** [comment]
And you will be. And I wanted to grow up here. But I was too late. As i joined (last year September) this community was already dying. And now we're in fact dead
