### ISSUE TITLE
Does WEA support genisys php7 now? What happen with this?

### ISSUE THREAD

**Issue by ViceEye** [LegendOfMCPE/WorldEditArt#20]
Genisys Crash Dump Fri Apr 29 15:39:58 MDT 2016

Error: 
File: /WorldEditArt_Dev.phar/src/WorldEditArt/WorldEditArt
Line: 79
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
此次出错由插件引起

Code:

Backtrace:
#0 /src/pocketmine/plugin/PharPluginLoader(66): pocketmine\plugin\PharPluginLoader->initPlugin(WorldEditArt\WorldEditArt object, pocketmine\plugin\PluginDescription object, string /home/multicraft/servers/server4160/plugins/WorldEditArt, string phar:///home/multicraft/servers/server4160/plugins/WorldEditArt_Dev.phar)
#1 /src/pocketmine/plugin/PluginManager(155): pocketmine\plugin\PharPluginLoader->loadPlugin(string phar:///home/multicraft/servers/server4160/plugins/WorldEditArt_Dev.phar)
#2 /src/pocketmine/plugin/PluginManager(333): pocketmine\plugin\PluginManager->loadPlugin(string /home/multicraft/servers/server4160/plugins/WorldEditArt_Dev.phar, array Array())
#3 /src/pocketmine/Server(1962): pocketmine\plugin\PluginManager->loadPlugins(string /home/multicraft/servers/server4160/plugins/)
#4 /src/pocketmine/PocketMine(467): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/multicraft/jar/pocketmine/genisys/Genisys.phar/, string /home/multicraft/servers/server4160/, string /home/multicraft/servers/server4160/plugins/, string unknown)
#5 (1): require_once(string phar:///home/multicraft/jar/pocketmine/genisys/Genisys.phar/src/pocketmine/PocketMine.php)

Genisys version: 1.1dev #343 [Protocol 60; API 2.0.0]
uname -a: Linux mc29 2.6.32-573.18.1.el6.x86_64 #1 SMP Tue Feb 9 22:46:17 UTC 2016 x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
加载的插件:
EssentialsPE 1.1.3vgphp7 by LegendsOfMCPE Team for API(s) 1.13.0

**Comment by ViceEye** [comment]
I dont understand what is wrong could u tell me how to do

**Comment by ghost** [comment]
Are you using latest version ?

**Comment by ViceEye** [comment]
Where is plugin.yml

**Comment by SOF3** [comment]
WorldEditArt never does support Genisys.
There is no `plugin.yml`. Please read the [Compiling section of the README file](https://github.com/LegendOfMCPE/WorldEditArt#compiling) -- you cannot compile the plugin into a phar using normal methods.
