### ISSUE TITLE
nobody can't connect to server :  logged out to timeout

### ISSUE THREAD

**Issue by teracube** [LegendOfMCPE/WorldEditArt#26]
Hi, 

with latest WorldEditArt Alpha7 plugin installed :

2017-08-11 [20:50:08] [Server thread/INFO]: Steve joined the game
2017-08-11 [20:50:34] [Server thread/INFO]: Steve left the game
2017-08-11 [20:50:34] [Server thread/INFO]: Steve[/109.XXX.XXX.XXX:50008] logged out due to timeout

without WorldEditArt : no problem

incompatibility with another plugin ?

PocketMine-MP 1.6.2dev-378

Other plugin installed
PurePerms 1.4.1-dev2; BlockPets 1.1.0; AllSigns 1.0.2; ItemCasePE 1.1.0-dev1; FactionsProBeta 1.4.4-dev2; xyz 1.0.3; EconomyAPI 5.7.1-dev2; CrateKeys 1.0.0; AlwaysSpawn 2.2.3-dev1; KillMoney 1.1.2; Jail 1.2.0; SimpleAuth 2.0.0-alpha7; SimpleAuthHelper 2.0.5-dev1; Slapper 1.3.5; PiggyCustomEnchants 1.0.2; essentialsTP 1.2.0-dev1; ChatToDiscord 1.1.0; iProtector 4.0.1#3.1b; Parkour 1.5.3; EconomyShop 2.0.8-dev2; PureChat 1.4.10-dev2

**Comment by SOF3** [comment]
WorldEditArt has not been finished yet.

Also, please set debug.level to 2 when you report bugs.

**Comment by teracube** [comment]
ok thanks
