### ISSUE TITLE
Client crash on join

### ISSUE THREAD

**Issue by PermissionError** [LegendOfMCPE/WorldEditArt#29]
Play clients crash on join when using WorldEditArt. As we have discussed before @SOF3 , I know this is weird, but I did a clean test and only left WorldEditArt-Epilson there and client crash on join. Tested with latest pmmp 7.0 build and latest WorldEditArt-Epilson build.
Can you reproduce this?

**Comment by PermissionError** [comment]
FYI, The console shows that the player joined then log out due ti timeout about 10 seconds after.

**Comment by SOF3** [comment]
So does this not happen if WorldEditArt is removed?

**Comment by PermissionError** [comment]
Yes, players join just fine
I'll enable debug 2 then post some logs
Wait, with the newest 7.0 build it throws an exception:
"unpack(): Type v: not enough input, need 2, have 0"

**Comment by PermissionError** [comment]
Having difficulty with VirtualBox copy/paste rn

**Comment by SOF3** [comment]
Yeah, I got that too. I'll fix this later.
I don't recommend using WorldEditArt right now, since it doesn't have any useful features yet.

**Comment by PermissionError** [comment]
[server.txt](https://github.com/LegendOfMCPE/WorldEditArt/files/1271946/server.txt)
That's the log
Oh just saw the comment thanks and I desprately need a WorldEdit Plugin and none of these I found work. Guess I'll have to learn php next huh?

**Comment by SOF3** [comment]
Protip: Currently, you can already abuse it to make area protection using selections + construction areas :D

**Comment by PermissionError** [comment]
lol
