### ISSUE TITLE
WorldEditArt & Composer Package

### ISSUE THREAD

**Issue by mrpwes** [LegendOfMCPE/WorldEditArt#33]
Can you update to Alpha-10 3.0.0 ? And can you add some composer package then we can easy update plugins

**Comment by SOF3** [comment]
Regarding composer package: Have you ever installed a PocketMine plugin with Composer?
Regarding ALPHA10 update: I'm not going to update until forms-api is merged.

**Comment by seaksezar** [comment]
Please update
