### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by TheEpicExplosion** [LegendOfMCPE/WorldEditArt#5]
Hey, I was wondering if your ever gonna continue work on WorldEditArt ? The thing is, Copy & Paste doesn't work, some commands are broken and sometimes it crashes the server. So, do you reckon you can fix it and take it out of beta?

**Comment by Tolo0** [comment]
I would happily donate just for a copy and paste fix

**Comment by PEMapModder** [comment]
Yes it will. And this is an entire rewrite that is still at elementary stage.
